services:
  php:
    build: .docker/php
    depends_on:
      - postgres
    ports:
      - 5173:5173
    volumes:
      - .:/var/www:cached

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  postgres:
    image: postgres:15
    ports:
      - 5431:5432
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
      - .docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql # optional if you want to run SQL at start
    environment:
      POSTGRES_USER: refactorian
      POSTGRES_PASSWORD: refactorian
      POSTGRES_DB: refactorian

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - .docker/redis/data:/data
    ports:
      - 6379:6379

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres
